Auditory First Version
in2workspace/in2-blockchain-connector-core pull request #5
Opened 2023-10-13 07:45 UTC by yaniaiciin2

ADD:
-> Now it creates auditory transaction registry when a event is generated
 -> Added JPA support for transaction DB
-> Created "Transaction" class
CHANGE:
-> Fixed some reactive controllers
-> Changed application.yml configuration for audit DB

2023-10-13 08:46 UTC, oriolcanadesin2 requested changes

2023-10-13 08:46 UTC, oriolcanadesin2 commented on src/main/java/es/in2/blockchain/connector/core/configuration/JpaConfig.java
> +    public LocalContainerEntityManagerFactoryBean entityManagerFactory(DataSource dataSource) {
@yaniaiciin2  'em' is not a good definition if we follow Clean Code.

2023-10-13 08:46 UTC, oriolcanadesin2 commented on src/main/java/es/in2/blockchain/connector/core/configuration/JpaConfig.java
> +    public JpaTransactionManager transactionManager(EntityManagerFactory entityManagerFactory) {
Same as above, JpaTrasnsactionManager jpaTransactionManager ;)

2023-10-13 08:46 UTC, oriolcanadesin2 commented on src/main/java/es/in2/blockchain/connector/core/domain/Transaction.java
> +    @GeneratedValue
Use strategy to add @GeneratedValue(strategy = GenerationType.UUID)

2023-10-13 08:46 UTC, oriolcanadesin2 commented on src/main/java/es/in2/blockchain/connector/core/domain/Transaction.java
> +    private String entityId;
This entityID is just the ID or all the location URL?

2023-10-13 08:46 UTC, oriolcanadesin2 commented on src/main/java/es/in2/blockchain/connector/core/domain/Transaction.java
> +    private String status;
Better if Status is an ENUM that brings distinct defined status types (RECEIVED, SENT, POST TO BLOCKCHAIN, ERROR, etc.)

2023-10-13 08:46 UTC, oriolcanadesin2 commented on src/main/java/es/in2/blockchain/connector/core/service/impl/TransactionServiceImpl.java
> +    @Autowired
@Autowired is forbidden. We use injection through constructor. Use the annotation @RequiredArgsConstructor

2023-10-13 08:48 UTC, yaniaiciin2 commented on src/main/java/es/in2/blockchain/connector/core/domain/Transaction.java
> +    private String entityId;
Just the ID

2023-10-16 11:37 UTC, oriolcanadesin2 requested changes

2023-10-16 11:37 UTC, oriolcanadesin2 commented on src/main/java/es/in2/blockchain/connector/core/utils/AuditStatus.java
> +    ERROR("ERROR"),
Delete ERROR status

2023-10-16 11:37 UTC, oriolcanadesin2 commented on src/main/java/es/in2/blockchain/connector/core/service/impl/TransactionServiceImpl.java
> +    @Override
Old:
	
	@Override
    public Transaction editTransactionAttribute(UUID id, String newAttributeValue) {

        Transaction existingTransaction = transactionRepository.findById(id);

        if (existingTransaction != null) {
            existingTransaction.setStatus(newAttributeValue);
            return transactionRepository.save(existingTransaction);
        }

        throw new NoSuchElementException("Transaction not found.");

    }
	
	New:
	
	@Override
    public Transaction editTransactionAttribute(UUID id, String newAttributeValue) {
        Transaction transactionFound = transactionRepository.findById(id);
		checkIfTransactionExist(transactionFound);
        existingTransaction.setStatus(newAttributeValue);
        return transactionRepository.save(existingTransaction);
    }
	
	private void checkIfTransactionExist(transactionFound Transaction) {
		// TODO: check if is null or empty
		if (transactionFound == null) { 
			throw new NoSuchElementException("Transaction not found.");
        }
	}

2023-10-16 11:37 UTC, oriolcanadesin2 commented on src/main/java/es/in2/blockchain/connector/core/service/impl/OnChainEntityServiceImpl.java
> +        Transaction transaction;
Received: datalocation

2023-10-16 11:37 UTC, oriolcanadesin2 commented on src/main/java/es/in2/blockchain/connector/core/service/impl/OnChainEntityServiceImpl.java
> +            transaction = transactionService.createTransaction(orionLdNotificationDTO.getId(), hashLinkService.extractHashLink(domeEvent.getDataLocation()), domeEvent.getDataLocation());
Created + Hash

2023-10-16 11:37 UTC, oriolcanadesin2 commented on src/main/java/es/in2/blockchain/connector/core/service/impl/OnChainEntityServiceImpl.java
> +            publishDomeEvent(domeEvent);
Published

2023-10-17 06:18 UTC, oriolcanadesin2 requested changes

2023-10-17 06:18 UTC, oriolcanadesin2 commented on src/main/java/es/in2/blockchain/connector/core/service/impl/OnChainEntityServiceImpl.java
> +            transactionService.editTransactionHash(transaction.getId(), domeEvent.getDataLocation());
Why we have 2 methods to edit a Transaction? Is it possible to group the methods into a single one, editTransaction()?

2023-10-19 10:19 UTC, merged